package com.sunyard.model;
// Generated 2018-1-30 20:08:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbArticle generated by hbm2java
 */
public class TbArticlehb implements java.io.Serializable {

	private Integer id;
	private String title;
	private String content;
	private Date createTime;
	private String author;

	public TbArticlehb() {
	}

	public TbArticlehb(String title, String content) {
		this.title = title;
		this.content = content;
	}

	public TbArticlehb(String title, String content, Date createTime, String author) {
		this.title = title;
		this.content = content;
		this.createTime = createTime;
		this.author = author;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

}
