package com.sunyard.model;
// Generated 2018-2-6 12:35:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbUser generated by hbm2java
 */
public class TbUserhb implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String emailAddress;
	private String password;
	private Date createTime;
	private Integer loginflag;

	public TbUserhb() {
	}

	public TbUserhb(String emailAddress, String password) {
		this.emailAddress = emailAddress;
		this.password = password;
	}

	public TbUserhb(String userName, String emailAddress, String password, Date createTime, Integer loginflag) {
		this.userName = userName;
		this.emailAddress = emailAddress;
		this.password = password;
		this.createTime = createTime;
		this.loginflag = loginflag;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getCreateTime() {
		return new Date(createTime.getDate());
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getLoginflag() {
		return this.loginflag;
	}

	public void setLoginflag(Integer loginflag) {
		this.loginflag = loginflag;
	}

}
